"""Glicmack DesignSpec — the central contract for text-to-game generation."""

from design_spec.models import (
    DesignSpec,
    ThemeSpec,
    PlayerSpec,
    WorldSpec,
    ObstacleSpec,
    CollectibleSpec,
    DifficultySpec,
    StyleSpec,
    AudioSpec,
    UISpec,
)
from design_spec.validators import DesignSpecValidator
from design_spec.confidence import ConfidenceScorer
from design_spec.enums import (
    Setting,
    Mood,
    PlayerArchetype,
    Ability,
    GroundType,
    ObstacleType,
    PatternStyle,
    CollectibleType,
    PowerupType,
    StylePack,
    LightingMood,
    PostProcessing,
    SfxPack,
    HudStyle,
    ScoreDisplay,
    FontStyle,
)

__all__ = [
    "DesignSpec",
    "ThemeSpec",
    "PlayerSpec",
    "WorldSpec",
    "ObstacleSpec",
    "CollectibleSpec",
    "DifficultySpec",
    "StyleSpec",
    "AudioSpec",
    "UISpec",
    "DesignSpecValidator",
    "ConfidenceScorer",
    "Setting",
    "Mood",
    "PlayerArchetype",
    "Ability",
    "GroundType",
    "ObstacleType",
    "PatternStyle",
    "CollectibleType",
    "PowerupType",
    "StylePack",
    "LightingMood",
    "PostProcessing",
    "SfxPack",
    "HudStyle",
    "ScoreDisplay",
    "FontStyle",
]
